seeing_the_world = ['romania', 'london', 'amsterdam', 'france']
print(seeing_the_world)
print(sorted(seeing_the_world))
print(seeing_the_world)
print(sorted(seeing_the_world, reverse=True))
print(seeing_the_world)
seeing_the_world.reverse()
print(seeing_the_world)
seeing_the_world.sort()
print(seeing_the_world)
seeing_the_world.sort(reverse=True)
print(seeing_the_world)